language: c
compiler: gcc
matrix:
  include:
  - script: scripts/test-codingstyle.sh
  - script: scripts/test-codingstyle-py.sh
    cache: pip
    install:
    - pip install --user pylint
    - pip install --user pycodestyle
    - pip install --user jsonschema
    - pip install --user jinja2
  - script: scripts/test-build.sh
    install:
    - pip install --user pybind11 nose2
    cache: ccache
    env:
    - TRAVIS_BUILD_TYPE=RelWithDebInfo
    addons:
      apt:
        packages:
        - libjson-c-dev
        - libhwloc-dev
        - uuid-dev
        - doxygen
  - script: scripts/test-build.sh
    install:
    - pip install --user pybind11 nose2
    cache: ccache
    env:
    - TRAVIS_BUILD_TYPE=Debug
    addons:
      apt:
        packages:
        - libjson-c-dev
        - libhwloc-dev
        - uuid-dev
        - doxygen
  - script: scripts/test-build.sh
    install:
    - pip install --user pybind11 nose2
    cache: ccache
    env:
    - TRAVIS_BUILD_TYPE=Release
    addons:
      apt:
        packages:
        - libjson-c-dev
        - libhwloc-dev
        - uuid-dev
        - doxygen
  - script: scripts/test-gtapi-mock-drv.sh
    install:
    - pip install --user pybind11 nose2
    cache: ccache
    addons:
      apt:
        packages:
        - libjson-c-dev
        - libhwloc-dev
        - uuid-dev
        - doxygen
  - script: scripts/build-tests-default.sh
    cache: ccache
    addons:
      apt:
        packages:
        - libjson-c-dev
        - libhwloc-dev
        - uuid-dev
        - doxygen
  - script: scripts/coverage-gtapi-mock-drv.sh
    install:
    - pip install --user pybind11 nose2
    cache:
      - ccache
      - pip
    addons:
      apt:
       packages:
        - libjson-c-dev
        - uuid-dev
        - doxygen
        - lcov
    before_install:
      - pip install --user cpp-coveralls
    after_success:
      - coveralls -l $TRAVIS_BUILD_DIR/coverage_gtapi_mock_drv/coverage.info.cleaned -E .*pybind11.*
  - script: scripts/build-documentation.sh
    cache: 
      - ccache
      - pip
    addons:
      apt:
       packages:
        - libjson-c-dev
        - libhwloc-dev
        - uuid-dev
        - doxygen
        - pandoc
    if: branch = master
    install:
      - pip install --user jinja2
      - pip install --user requests[security]
    before_install:
    - wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-1-amd64.deb
    - sudo dpkg -i pandoc-2.1.1-1-amd64.deb
  - script: echo "coverity scan"
    before_install: 
      - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    addons:
      coverity_scan:
      project:
      name: "OPAE/opae-sdk"
      description: "Open Programmable Acceleration Engine SDK"
    notification_email: nakul.korde@intel.com
    build_command_prepend: mkdir coverity_scan && pushd coverity_scan && cmake ../
    build_command: make
    branch_pattern: coverity_scan

env:
  global:
    - secure: ejmtge9PpCihZ92AolJhTBWGTYUU49dzwR10xBd62JfDSXWs8UYu3FSGodLQcMm4XdaM0uDthJ1MzvP/CphgMCOIyzVr6XLF8JFLVLw6cP1P0Q5Kgj1qN9f8DZL3VrgyRSL7lRuxQt4qP8eXLlksEAi+PKrka2hsNnUtoX8JBYHeeos7b+Q4vq4d/PzpIrhrYIQy1RlatAAhGG8JsD3R2WdkNwK3kGUvcAwZirROfRAf+xaPRKCTHtRfNehTCu93v9n1uYdxDAWw7RJOjjYp+HUGj7XUTi28D7kcz5zOKp6Ny7Cgf3SgQqwK4xF+Jidk/g5i9V8D0Qi0oplbD6vekp0zVU6k8IWLZgtfqw9CnRV2Tv7e7a7oMUsFoKEW3pT/U1lU1fKuEddTUlf8myMoAm6VcEXXtboz2xP9svpNvDjnATU8CTtN1eEdrOpmI6FjYZv133twkfP61bEKgv05w8416/jvcil3CXnzVGFkbO2oXCr1uWe3t/JjEon8W+rgnxl9uC/QeEd1uFwOi3/UBB+ZQp8khbMz68iRSux7g+mGiZ6Ezbr0WaSIz6ZiliFykLCbpyAJduHIUCc1chF20Xq8105D/Ue4nCOnI/h/vC/BsQ5Ms+VAYk1QHPgNXKEc2pteVxHaTg7c6qoHsBV+NTkdd4QJvNuS+jzZsxao7JQ=
    - secure: "byMBk+Hpe1yWqNnixvWOa6NPgzskDVfNofA75NuUscizURNIK/oHNzyqiOdzTVjvK3CzTWfIOBhrd2h6DuTlD2jXByBejSss52o9O+hhA4ZVxCL5/BL8Rbvt/iR4DPpFMQX+SI+UMezzcVOQhPQptPPhmjDe8Cw0xEaX1IIznipUrwb+8QBpJXXszdXJSSfpUUf+d4Y6pPK5wV2STyYes3tgb6C1jQhsGh14u7o3EKpEQuoI/yuLE2iKNaWIq5PFOm6qiFqWImWk9TS0SAd67vkTvuFTekNnqBOUMx6XM851TmRS6iKQ798GjeAms76hXRKH2f/UJIsNst91/MHWbbd9ICa9bSB6LizSfbCe37CIaoUDArZFUKl5s3fdZkuc6LDK+kXYeMe9BMH5sMJUU+FZtfoVh9pkcJjhF1ApqWcj2d9RnKXUM9KH+Ol6HcAb1OqxJLTu+jdSAnkdhfXzwl6KCjAgnP2IT0VT4dVWv4enxOvOTy/+MjT88T7DvilkKdYFyMZlm/L+sKkkNLAbwVdJTYY22MsuzCCeEDhUY0X0bcpZ7tTjv/bNOogjOYzMUW9e8ZOR2RJLX3xXEhM2ClZkt7JcBzqu3i/IYL1JoRk8KF3gUTRljHCtsqgGtH8cmKn8sWgLN66TAf/ZbX7Hoqjk1QfZTiU5IEgo39EtvOk="
